I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 348, in script
    voice rena_hehh
  File "renpy/common/00voice.rpy", line 534, in execute_voice
    fn = _audio_eval(fn)
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script.rpy", line 348, in <module>
    voice rena_hehh
NameError: name 'rena_hehh' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 348, in script
    voice rena_hehh
  File "renpy/ast.py", line 1969, in execute
    self.call("execute")
  File "renpy/ast.py", line 1957, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/00voice.rpy", line 534, in execute_voice
    fn = _audio_eval(fn)
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 348, in <module>
    voice rena_hehh
NameError: name 'rena_hehh' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.6.1668
Higurashi Gou 
Sun Jun  6 15:04:23 2021
